export { useBoxDrag } from "./model/useBoxDrag";
export type { BoxDragState, BoxDragCallbacks, DragRoom, } from "./model/useBoxDrag";
export { computeStacks, overlapsZone } from "./model/placement";
export type { BoxDims, PlacedBoxDims, BoxStack, XYZone, PartitionDims, } from "./model/placement";
export { isInPartitionGap } from "./model/placement";
export { overlapsPartitionFootprint } from "./model/placement";
export { DraggableBox } from "./ui/DraggableBox";
export type { DraggableBoxProps } from "./ui/DraggableBox";
export { BoxDragGhost } from "./ui/BoxDragGhost";
export { darkenColor, isColorTooDark, getRelativeLuminance, getContrastColor, getBorderColor, } from "./lib/color";
export { getTransparentDragImage } from "@/shared/lib/drag-image";
export { boxHighlightCn } from "./lib/box-highlight";
export type { BoxHighlightState } from "./lib/box-highlight";
